#!/bin/bash
# auto-checkpoint.sh — Stop hook: persist session state to .project/checkpoint.md
#
# WHY THIS EXISTS:
# /compact drops the "why" behind decisions. Session restarts lose everything.
# This hook writes a structured bridge file that the next session reads FIRST
# (per CLAUDE.md), so long-lived work survives session boundaries without
# human intervention.
#
# Reference: Anthropic "Context Reset with structured handoff". idea-factory
# templates/documents/handoff.md.tmpl provides the structure template.
#
# TRIGGER: Stop event, or PostToolUse at 80%+ saturation (--forced flag)
# PRINCIPLE: Always exit 0. Never block session shutdown.

INPUT=$(cat 2>/dev/null)
FORCED_MODE=0
[ "$1" = "--forced" ] && FORCED_MODE=1

REPO_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
CHECKPOINT="$REPO_ROOT/.project/checkpoint.md"
mkdir -p "$(dirname "$CHECKPOINT")" 2>/dev/null

cd "$REPO_ROOT" 2>/dev/null || exit 0

NOW=$(date "+%Y-%m-%d %H:%M")
TRIGGER="Session Stop"
[ "$FORCED_MODE" -eq 1 ] && TRIGGER="Context 80% saturation"

CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

RECENT_COMMITS=$(git log --oneline -20 2>/dev/null | sed 's/^/- /' || echo "- (git log unavailable)")

RECENT_DECISIONS=""
if [ -f ".project/decisions.md" ]; then
  RECENT_DECISIONS=$(tail -40 .project/decisions.md 2>/dev/null)
fi

ACTIVE_ISSUES=""
if command -v gh &>/dev/null; then
  ACTIVE_ISSUES=$(gh issue list --state open --limit 10 --json number,title 2>/dev/null \
    | jq -r '.[] | "- #\(.number) \(.title)"' 2>/dev/null || echo "- (gh unavailable)")
fi

ACTIVE_PRS=""
if command -v gh &>/dev/null; then
  ACTIVE_PRS=$(gh pr list --state open --limit 10 --json number,title,headRefName 2>/dev/null \
    | jq -r '.[] | "- #\(.number) [\(.headRefName)] \(.title)"' 2>/dev/null || echo "- (gh unavailable)")
fi

UNCOMMITTED=$(git status --porcelain 2>/dev/null | head -20)
[ -z "$UNCOMMITTED" ] && UNCOMMITTED="(clean)"

CURRENT_PHASE="unknown"
if [ -f ".project/phase-tracker.md" ]; then
  CURRENT_PHASE=$(grep -m1 -E "^## |^# Current" .project/phase-tracker.md 2>/dev/null | head -1 | sed 's/^#* //')
  [ -z "$CURRENT_PHASE" ] && CURRENT_PHASE="(phase-tracker.md exists but no heading found)"
fi

cat > "$CHECKPOINT" <<EOF
# Session Checkpoint

> Auto-generated by \`.claude/hooks/auto-checkpoint.sh\` — DO NOT edit manually.
> New sessions MUST read this file first (see CLAUDE.md).
> Trigger: ${TRIGGER}

## Metadata
- **Updated**: ${NOW}
- **Branch**: \`${CURRENT_BRANCH}\`
- **Current Phase**: ${CURRENT_PHASE}

## Uncommitted Changes
\`\`\`
${UNCOMMITTED}
\`\`\`

## Recent Commits (last 20)
${RECENT_COMMITS}

## Open Issues
${ACTIVE_ISSUES:-"- (none or gh unavailable)"}

## Open PRs
${ACTIVE_PRS:-"- (none or gh unavailable)"}

## Recent Decisions (tail of .project/decisions.md)
\`\`\`
${RECENT_DECISIONS:-"(no decisions.md or empty)"}
\`\`\`

## Must-Read Files for New Session
1. \`CLAUDE.md\` — 프로젝트 헌법
2. \`.project/backlog.md\` — 작업 목록
3. \`.project/decisions.md\` — 결정 이력 (재논의 금지)
4. \`.project/quality-baseline.md\` — 품질 래칫
5. \`.project/phase-tracker.md\` — 현재 Phase
6. \`src/components/home/HOME_CONTRACT.md\` — 홈 컴포넌트 보호 계약

## Next Session: Resume Checklist
- [ ] 위 Must-Read 6개 파일 읽기
- [ ] 현재 브랜치와 uncommitted 변경사항 확인
- [ ] Open Issues/PRs 중 진행 중이던 항목 이어가기
- [ ] decisions.md에 이미 기록된 결정은 재논의 금지
EOF

exit 0
