#!/usr/bin/env bash
# create-pr.sh — PR 생성 전 전체 절차 자동 실행
# 사용법: npm run pr -- "PR 제목"
# 또는: bash scripts/create-pr.sh "PR 제목"
set -euo pipefail

TITLE="${1:-}"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ -z "$TITLE" ]; then
  echo -e "${RED}[pr] PR 제목을 입력하세요: bash scripts/create-pr.sh \"PR 제목\"${NC}"
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo -e "${RED}[pr] main 브랜치에서는 PR을 생성할 수 없습니다.${NC}"
  exit 1
fi

echo -e "${GREEN}[pr] === 1/4 빌드 확인 ===${NC}"
npm run build || { echo -e "${RED}[pr] 빌드 실패${NC}"; exit 1; }

echo ""
echo -e "${GREEN}[pr] === 2/4 Codex gate ===${NC}"
CODEX_STATUS="SKIPPED (codex CLI 미설치)"
if command -v codex &>/dev/null; then
  npm run review:gate || {
    echo -e "${YELLOW}[pr] Codex gate BLOCK — 수정 후 재실행하세요${NC}"
    exit 1
  }
  CODEX_STATUS="PASS"
else
  echo -e "${YELLOW}[pr] Codex CLI 미설치 — 스킵${NC}"
fi

echo ""
echo -e "${GREEN}[pr] === 3/4 PR 생성 ===${NC}"
PR_URL=$(gh pr create --title "$TITLE" --body "$(cat <<EOF
## 독립 리뷰 결과

### code-reviewer (Claude)
- PR 생성 전 code-reviewer 에이전트 리뷰 필요 (create-pr.sh에서 자동 호출 불가 — 수동 실행 후 여기에 기록)

### Codex gate (OpenAI)
- ${CODEX_STATUS}

---
🤖 Generated by Claude Code [claude-sonnet-4-6]
EOF
)" 2>&1 | grep "https://")

echo -e "${GREEN}[pr] PR 생성: $PR_URL${NC}"

echo ""
echo -e "${GREEN}[pr] === 4/4 봇 리뷰 대기 (3분) ===${NC}"
PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$')
sleep 180

# 봇 리뷰 확인 — API 실패와 리뷰 없음을 분리
if ! REVIEWS=$(gh api "repos/gguloadoong/market-dashboard-v2/pulls/$PR_NUM/reviews" --jq '.[] | "\(.user.login): \(.state)"' 2>/dev/null); then
  echo -e "${RED}[pr] 봇 리뷰 조회 실패 (권한/네트워크 오류). 수동 확인 후 머지하세요.${NC}"
  exit 1
fi

if [ -z "$REVIEWS" ]; then
  echo -e "${YELLOW}[pr] 봇 리뷰 미도착 — PR에 '봇 미응답' 기록${NC}"
  gh pr comment "$PR_NUM" --body "봇 미응답 (3분 대기). 독립 리뷰 결과만으로 머지 가능." 2>/dev/null
else
  echo -e "${GREEN}[pr] 봇 리뷰 도착:${NC}"
  echo "$REVIEWS"
  echo ""
  echo -e "${YELLOW}[pr] ⚠️ 봇 리뷰에 응답 코멘트를 남기세요!${NC}"
  echo -e "${YELLOW}[pr] gh api repos/gguloadoong/market-dashboard-v2/pulls/$PR_NUM/comments 로 상세 확인${NC}"
fi

echo ""
echo -e "${GREEN}[pr] ✅ PR 생성 완료. 봇 리뷰 응답 후 머지하세요.${NC}"
