#!/usr/bin/env bash
# create-pr.sh — PR 생성 전 전체 절차 자동 실행
# 사용법: npm run pr -- "PR 제목"
# 또는: bash scripts/create-pr.sh "PR 제목"
set -euo pipefail

TITLE="${1:-}"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ -z "$TITLE" ]; then
  echo -e "${RED}[pr] PR 제목을 입력하세요: bash scripts/create-pr.sh \"PR 제목\"${NC}"
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo -e "${RED}[pr] main 브랜치에서는 PR을 생성할 수 없습니다.${NC}"
  exit 1
fi

echo -e "${GREEN}[pr] === 1/5 빌드 확인 ===${NC}"
npm run build || { echo -e "${RED}[pr] 빌드 실패${NC}"; exit 1; }

# ─── 2/5 code-reviewer 결과 확인 (강제 입력) ──────────────────────────────
echo ""
echo -e "${GREEN}[pr] === 2/5 code-reviewer 결과 확인 ===${NC}"
echo -e "${YELLOW}[pr] PR 생성 전 code-reviewer 에이전트를 실행했습니까?${NC}"
echo -e "${YELLOW}[pr] 크리티컬/버그 이슈가 있었다면 수정 완료 여부를 포함해 입력하세요.${NC}"
echo -e "${YELLOW}[pr] 예: 크리티컬 없음 / [채택] useMemo 의존성 수정 / [기각] 스타일 제안 — 1회성 사용${NC}"
echo -n "[pr] code-reviewer 처리 결과 입력 (빈 입력 시 중단): "
read -r CODE_REVIEWER_RESULT

if [ -z "$CODE_REVIEWER_RESULT" ]; then
  echo -e "${RED}[pr] code-reviewer 결과 미입력 — PR 생성 중단${NC}"
  echo -e "${RED}[pr] code-reviewer 실행 후 결과를 입력하세요.${NC}"
  exit 1
fi

# ─── 3/5 Codex gate ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[pr] === 3/5 Codex gate ===${NC}"
CODEX_STATUS="SKIPPED (codex CLI 미설치)"
CODEX_ISSUES_DECISION=""

if command -v codex &>/dev/null; then
  # Codex gate 실행 및 출력 캡처
  set +e
  CODEX_OUTPUT=$(npm run review:gate 2>&1)
  CODEX_EXIT=$?
  set -e
  echo "$CODEX_OUTPUT"

  # BLOCK 체크
  if [ "$CODEX_EXIT" -ne 0 ] || echo "$CODEX_OUTPUT" | grep -q "BLOCK"; then
    echo -e "${YELLOW}[pr] Codex gate BLOCK — 수정 후 재실행하세요${NC}"
    exit 1
  fi

  # P1/P2/HIGH/CRITICAL 이슈 추출
  CODEX_ISSUES=$(echo "$CODEX_OUTPUT" | grep -E '^\s*-\s*\[P[12]\]|\[HIGH\]|\[CRITICAL\]' || true)

  if [ -n "$CODEX_ISSUES" ]; then
    echo ""
    echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
    echo -e "${RED}[pr] ⛔ Codex 지적사항 발견 — PR 생성 전 처리 결정 필수  ⛔${NC}"
    echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
    echo -e "${YELLOW}[pr] 발견된 지적사항:${NC}"
    echo "$CODEX_ISSUES"
    echo ""
    echo -e "${YELLOW}[pr] 각 항목에 대해 채택(수정 완료) 또는 기각(사유)을 입력하세요.${NC}"
    echo -e "${YELLOW}[pr] 예: [채택] xxx 수정 완료 / [기각] yyy — 현재 범위 밖, 백로그 등록${NC}"
    echo -e "${YELLOW}[pr] 빈 입력 시 PR 생성 중단됩니다.${NC}"
    echo -n "[pr] Codex 지적사항 처리 결과 입력: "
    read -r CODEX_ISSUES_DECISION

    if [ -z "$CODEX_ISSUES_DECISION" ]; then
      echo -e "${RED}[pr] 처리 결과 미입력 — PR 생성 중단${NC}"
      exit 1
    fi

    CODEX_STATUS="PASS (지적사항 처리: ${CODEX_ISSUES_DECISION})"
  else
    CODEX_STATUS="PASS"
  fi
else
  echo -e "${YELLOW}[pr] Codex CLI 미설치 — 스킵${NC}"
fi

# ─── 4/5 PR 생성 ─────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[pr] === 4/5 PR 생성 ===${NC}"

REVIEW_BODY="## 독립 리뷰 결과

### code-reviewer (Claude)
${CODE_REVIEWER_RESULT}

### Codex gate (OpenAI)
- ${CODEX_STATUS}

---
🤖 Generated by Claude Code [claude-sonnet-4-6]"

PR_URL=$(gh pr create --title "$TITLE" --body "$REVIEW_BODY" 2>&1 | grep "https://")

echo -e "${GREEN}[pr] PR 생성: $PR_URL${NC}"

PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$')
REPO="gguloadoong/market-dashboard-v2"

# ─── 5/5 봇 리뷰 폴링 ────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[pr] === 5/5 봇 리뷰 폴링 (최대 15분) ===${NC}"
echo -e "${YELLOW}[pr] Gemini·Copilot·CodeRabbit 리뷰 도착까지 대기 중...${NC}"

MAX_ITER=30
INTERVAL=30
ARRIVED=0

for i in $(seq 1 $MAX_ITER); do
  sleep $INTERVAL

  REVIEW_COUNT=$(gh api "repos/${REPO}/pulls/${PR_NUM}/reviews" --jq 'length' 2>/dev/null || echo "0")
  CR_COUNT=$(gh api "repos/${REPO}/issues/${PR_NUM}/comments" --jq '[.[] | select(.user.login | contains("coderabbit"))] | length' 2>/dev/null || echo "0")

  TOTAL=$((REVIEW_COUNT + CR_COUNT))
  ELAPSED=$((i * INTERVAL))

  if [ "$TOTAL" -gt 0 ]; then
    ARRIVED=1
    echo ""
    echo -e "${GREEN}[pr] ✅ 봇 리뷰 ${TOTAL}건 도착! (${ELAPSED}s 경과)${NC}"
    break
  fi

  echo -e "[pr] 대기 중... ${ELAPSED}s / $((MAX_ITER * INTERVAL))s (리뷰: ${TOTAL}건)"
done

if [ "$ARRIVED" -eq 0 ]; then
  echo -e "${YELLOW}[pr] ⏰ 15분 대기 종료 — 봇 미응답${NC}"
  gh pr comment "$PR_NUM" --body "봇 미응답 (15분 대기 초과). 독립 리뷰 결과만으로 머지 가능." 2>/dev/null || true
  echo -e "${GREEN}[pr] ✅ PR 생성 완료: $PR_URL${NC}"
  exit 0
fi

echo ""
echo -e "${GREEN}[pr] ─── 봇 리뷰 상세 내용 ───${NC}"

gh api "repos/${REPO}/pulls/${PR_NUM}/reviews" --jq '.[] | "[\(.user.login)] \(.state)\n\(.body | .[0:400])\n---"' 2>/dev/null || true

gh api "repos/${REPO}/issues/${PR_NUM}/comments" \
  --jq '[.[] | select(.user.login | contains("coderabbit"))] | .[] | "[\(.user.login)]\n\(.body | .[0:600])\n---"' 2>/dev/null || true

INLINE_COUNT=$(gh api "repos/${REPO}/pulls/${PR_NUM}/comments" --jq 'length' 2>/dev/null || echo "0")
if [ "$INLINE_COUNT" -gt 0 ]; then
  echo ""
  echo -e "${YELLOW}[pr] 인라인 코멘트 ${INLINE_COUNT}건:${NC}"
  gh api "repos/${REPO}/pulls/${PR_NUM}/comments" \
    --jq '.[] | "[\(.user.login)] \(.path):\(.line // "?") — \(.body | .[0:200])\n---"' 2>/dev/null || true
fi

echo ""
echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
echo -e "${RED}[pr] ⚠️  봇 리뷰 응답 필수 — 지금 즉시 처리하세요  ⚠️${NC}"
echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
echo -e "${YELLOW}[pr] HIGH/CRITICAL → 코드 수정 후 push${NC}"
echo -e "${YELLOW}[pr] MEDIUM/LOW → 채택/기각 판단 후 PR 코멘트 작성${NC}"
echo -e "${YELLOW}[pr] 응답 없이 머지 금지 (CLAUDE.md 규칙)${NC}"
echo -e "${GREEN}[pr] PR: $PR_URL${NC}"
