#!/usr/bin/env bash
# create-pr.sh — PR 생성 전 전체 절차 자동 실행
# 사용법: npm run pr -- "PR 제목"
# 또는: bash scripts/create-pr.sh "PR 제목"
set -euo pipefail

TITLE="${1:-}"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ -z "$TITLE" ]; then
  echo -e "${RED}[pr] PR 제목을 입력하세요: bash scripts/create-pr.sh \"PR 제목\"${NC}"
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo -e "${RED}[pr] main 브랜치에서는 PR을 생성할 수 없습니다.${NC}"
  exit 1
fi

echo -e "${GREEN}[pr] === 1/4 빌드 확인 ===${NC}"
npm run build || { echo -e "${RED}[pr] 빌드 실패${NC}"; exit 1; }

echo ""
echo -e "${GREEN}[pr] === 2/4 Codex gate ===${NC}"
CODEX_STATUS="SKIPPED (codex CLI 미설치)"
if command -v codex &>/dev/null; then
  npm run review:gate || {
    echo -e "${YELLOW}[pr] Codex gate BLOCK — 수정 후 재실행하세요${NC}"
    exit 1
  }
  CODEX_STATUS="PASS"
else
  echo -e "${YELLOW}[pr] Codex CLI 미설치 — 스킵${NC}"
fi

echo ""
echo -e "${GREEN}[pr] === 3/4 PR 생성 ===${NC}"
PR_URL=$(gh pr create --title "$TITLE" --body "$(cat <<EOF
## 독립 리뷰 결과

### code-reviewer (Claude)
- PR 생성 전 code-reviewer 에이전트 리뷰 필요 (create-pr.sh에서 자동 호출 불가 — 수동 실행 후 여기에 기록)

### Codex gate (OpenAI)
- ${CODEX_STATUS}

---
🤖 Generated by Claude Code [claude-sonnet-4-6]
EOF
)" 2>&1 | grep "https://")

echo -e "${GREEN}[pr] PR 생성: $PR_URL${NC}"

PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$')
REPO="gguloadoong/market-dashboard-v2"

echo ""
echo -e "${GREEN}[pr] === 4/4 봇 리뷰 폴링 (최대 15분) ===${NC}"
echo -e "${YELLOW}[pr] Gemini·Copilot·CodeRabbit 리뷰 도착까지 대기 중...${NC}"

# 30초 간격 × 30회 = 최대 15분 폴링
MAX_ITER=30
INTERVAL=30
ARRIVED=0

for i in $(seq 1 $MAX_ITER); do
  sleep $INTERVAL

  # 리뷰 (Approve/Comment/Request Changes)
  REVIEW_COUNT=$(gh api "repos/${REPO}/pulls/${PR_NUM}/reviews" --jq 'length' 2>/dev/null || echo "0")
  # CodeRabbit은 issue comment로 오는 경우가 있어 함께 확인
  CR_COUNT=$(gh api "repos/${REPO}/issues/${PR_NUM}/comments" --jq '[.[] | select(.user.login | contains("coderabbit"))] | length' 2>/dev/null || echo "0")

  TOTAL=$((REVIEW_COUNT + CR_COUNT))
  ELAPSED=$((i * INTERVAL))

  if [ "$TOTAL" -gt 0 ]; then
    ARRIVED=1
    echo ""
    echo -e "${GREEN}[pr] ✅ 봇 리뷰 ${TOTAL}건 도착! (${ELAPSED}s 경과)${NC}"
    break
  fi

  echo -e "[pr] 대기 중... ${ELAPSED}s / $((MAX_ITER * INTERVAL))s (리뷰: ${TOTAL}건)"
done

if [ "$ARRIVED" -eq 0 ]; then
  echo -e "${YELLOW}[pr] ⏰ 15분 대기 종료 — 봇 미응답${NC}"
  gh pr comment "$PR_NUM" --body "봇 미응답 (15분 대기 초과). 독립 리뷰 결과만으로 머지 가능." 2>/dev/null || true
  echo -e "${GREEN}[pr] ✅ PR 생성 완료: $PR_URL${NC}"
  exit 0
fi

echo ""
echo -e "${GREEN}[pr] ─── 봇 리뷰 상세 내용 ───${NC}"

# Gemini / Copilot 리뷰
gh api "repos/${REPO}/pulls/${PR_NUM}/reviews" --jq '.[] | "[\(.user.login)] \(.state)\n\(.body | .[0:400])\n---"' 2>/dev/null || true

# CodeRabbit (issue comment)
gh api "repos/${REPO}/issues/${PR_NUM}/comments" \
  --jq '[.[] | select(.user.login | contains("coderabbit"))] | .[] | "[\(.user.login)]\n\(.body | .[0:600])\n---"' 2>/dev/null || true

# inline 코멘트 요약
INLINE_COUNT=$(gh api "repos/${REPO}/pulls/${PR_NUM}/comments" --jq 'length' 2>/dev/null || echo "0")
if [ "$INLINE_COUNT" -gt 0 ]; then
  echo ""
  echo -e "${YELLOW}[pr] 인라인 코멘트 ${INLINE_COUNT}건:${NC}"
  gh api "repos/${REPO}/pulls/${PR_NUM}/comments" \
    --jq '.[] | "[\(.user.login)] \(.path):\(.line // "?") — \(.body | .[0:200])\n---"' 2>/dev/null || true
fi

echo ""
echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
echo -e "${RED}[pr] ⚠️  봇 리뷰 응답 필수 — 지금 즉시 처리하세요  ⚠️${NC}"
echo -e "${RED}[pr] ══════════════════════════════════════════${NC}"
echo -e "${YELLOW}[pr] HIGH/CRITICAL → 코드 수정 후 push${NC}"
echo -e "${YELLOW}[pr] MEDIUM/LOW → 채택/기각 판단 후 PR 코멘트 작성${NC}"
echo -e "${YELLOW}[pr] 응답 없이 머지 금지 (CLAUDE.md 규칙)${NC}"
echo -e "${GREEN}[pr] PR: $PR_URL${NC}"
