#!/usr/bin/env bash
# review-summary.sh — Review Summary Auto-Post to PR
# Generalized from market-dashboard-v5
#
# Usage: bash scripts/review-summary.sh
#   1. Detect PR number for current branch
#   2. Re-run code-reviewer -> extract verdict
#   3. Run Codex gate (if available) -> extract verdict
#   4. Post combined review summary as PR comment

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

BRANCH=$(git rev-parse --abbrev-ref HEAD)
SAFE_BRANCH="${BRANCH//\//-}"
REVIEW_FILE=".tmp/code-review-${SAFE_BRANCH}.md"

echo -e "${BLUE}[review-summary] Branch: ${BRANCH}${NC}"

# --- 1. Detect PR ---
PR_NUMBER=$(gh pr view "$BRANCH" --json number --jq '.number' 2>/dev/null || echo "")
if [ -z "$PR_NUMBER" ]; then
  echo -e "${RED}[review-summary] No open PR for this branch.${NC}"
  exit 1
fi
echo -e "${GREEN}[review-summary] PR #${PR_NUMBER}${NC}"

# --- 2. Code-reviewer verdict ---
echo -e "${BLUE}[review-summary] Checking code-reviewer artifact...${NC}"
OPUS_VERDICT="UNKNOWN"
OPUS_LINE="? No artifact found"

if [ -f "$REVIEW_FILE" ]; then
  _raw=$(grep -oE "VERDICT: (PASS|BLOCK)" "$REVIEW_FILE" | tail -1 || true)
  OPUS_VERDICT=$(echo "$_raw" | cut -d' ' -f2)
  [ -z "$OPUS_VERDICT" ] && OPUS_VERDICT="UNKNOWN"

  if [ "$OPUS_VERDICT" = "PASS" ]; then
    OPUS_LINE="PASS"
  else
    OPUS_SUMMARY=$(grep -m1 "\[CRITICAL\]\|\[HIGH\]" "$REVIEW_FILE" | head -c 120 || echo "see artifact")
    OPUS_LINE="BLOCK — ${OPUS_SUMMARY:-needs fix}"
  fi
fi

# --- 3. Codex gate verdict ---
CODEX_VERDICT="SKIP"
CODEX_LINE="SKIP (codex CLI not installed)"

if command -v codex &>/dev/null; then
  echo -e "${BLUE}[review-summary] Running Codex gate...${NC}"
  CODEX_TMP=$(mktemp)
  if codex exec review --base origin/main --output-last-message "$CODEX_TMP" --full-auto 2>/dev/null; then
    CODEX_TEXT="$(cat "$CODEX_TMP")"
    if echo "$CODEX_TEXT" | grep -iqE "DECISION:[[:space:]]*BLOCK|patch is incorrect"; then
      CODEX_VERDICT="BLOCK"
      CODEX_LINE="BLOCK"
    else
      CODEX_VERDICT="PASS"
      CODEX_LINE="PASS"
    fi
  else
    CODEX_LINE="SKIP (codex execution failed)"
  fi
  rm -f "$CODEX_TMP"
fi

# --- 4. Post comment ---
BOT_TABLE="${BOT_REVIEW_TABLE:-"| (bot) | (issue) | [accept] / [reject] | (action) |"}"

COMMENT="## Review Summary

### Bot Review Accept/Reject
| Bot | Issue | Decision | Action |
|---|---|---|---|
${BOT_TABLE}

### Final Review

> **code-reviewer (Claude Opus)**: ${OPUS_LINE}
> **Codex Gate**: ${CODEX_LINE}

---
Generated by Claude Code"

echo -e "${BLUE}[review-summary] Posting to PR #${PR_NUMBER}...${NC}"
gh pr comment "$PR_NUMBER" --body "$COMMENT"

echo -e "${GREEN}[review-summary] Done — Opus: ${OPUS_VERDICT} / Codex: ${CODEX_VERDICT}${NC}"

if [ "$OPUS_VERDICT" != "PASS" ] || { [ "$CODEX_VERDICT" != "PASS" ] && [ "$CODEX_VERDICT" != "SKIP" ]; }; then
  echo -e "${RED}[review-summary] BLOCK detected — fix before merge${NC}"
  exit 1
fi
