#!/usr/bin/env bash
# review-summary.sh — 리뷰 종합 코멘트 자동 생성 & GitHub PR에 게시
#
# 사용법: npm run review:summary
#   1. 현재 브랜치의 PR 번호 자동 감지
#   2. code-reviewer (Opus) 재실행 → 결과 추출
#   3. Codex gate 재실행 → 결과 추출
#   4. 리뷰 종합 코멘트 생성 → gh pr comment 게시
#
# 봇 리뷰(Gemini/Copilot/CodeRabbit) 채택/기각 내용은 스크립트 실행 전
# BOT_REVIEW_TABLE 환경변수로 전달하거나, 생성된 코멘트에 직접 편집 가능.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

BRANCH=$(git rev-parse --abbrev-ref HEAD)
SAFE_BRANCH="${BRANCH//\//-}"
REVIEW_FILE=".tmp/code-review-${SAFE_BRANCH}.md"
CODEX_TMP="$(mktemp)"
trap 'rm -f "$CODEX_TMP"' EXIT

echo -e "${BLUE}[review-summary] 브랜치: ${BRANCH}${NC}"

# ── 1. PR 번호 감지 ──────────────────────────────────────────────────────────
PR_NUMBER=$(gh pr view "$BRANCH" --json number --jq '.number' 2>/dev/null || echo "")
if [ -z "$PR_NUMBER" ]; then
  echo -e "${RED}[review-summary] 현재 브랜치에 열린 PR 없음. PR 생성 후 실행하세요.${NC}"
  exit 1
fi
echo -e "${GREEN}[review-summary] PR #${PR_NUMBER} 감지${NC}"

# ── 2. code-reviewer (Opus) 재실행 ───────────────────────────────────────────
echo -e "${BLUE}[review-summary] code-reviewer (Opus) 실행 중...${NC}"
bash scripts/run-code-reviewer.sh || true  # BLOCK 시에도 artifact는 저장됨 — 스크립트 중단 방지

if [ ! -f "$REVIEW_FILE" ]; then
  echo -e "${RED}[review-summary] 리뷰 artifact 없음: ${REVIEW_FILE}${NC}"
  exit 1
fi

# verdict 추출
OPUS_VERDICT=$(grep -oE "VERDICT: (PASS|BLOCK)" "$REVIEW_FILE" | head -1 | cut -d' ' -f2 || echo "UNKNOWN")
# 주요 소견: HIGH/CRITICAL 태그 줄 또는 요약 첫 줄
OPUS_SUMMARY=$(grep -m1 "PASS\|수정 완료\|이상 없음\|지적사항 없음" "$REVIEW_FILE" \
  | sed 's/\*\*//g' | head -c 100 || echo "세부 내용은 artifact 참조")
if [ "$OPUS_VERDICT" = "PASS" ]; then
  OPUS_LINE="✅ PASS${OPUS_SUMMARY:+ — ${OPUS_SUMMARY}}"
else
  OPUS_LINE="🚫 BLOCK — 재수정 필요"
fi

# ── 3. Codex gate 재실행 ─────────────────────────────────────────────────────
CODEX_VERDICT="SKIP"
CODEX_LINE="⏭️ SKIP (codex CLI 미설치)"

if command -v codex &>/dev/null; then
  echo -e "${BLUE}[review-summary] Codex gate 실행 중...${NC}"
  # 플래그 검증: --output-last-message(-o), --full-auto 모두 codex exec review --help에서 확인됨
  if codex exec review --base origin/main --output-last-message "$CODEX_TMP" --full-auto 2>/dev/null; then
    CODEX_TEXT="$(cat "$CODEX_TMP")"
    # BLOCK 판정: DECISION:BLOCK, 줄 시작 [P0]/[P1] 태그, JSON "patch is incorrect" 패턴 감지
    # [P0]/[P1]은 줄 시작(^[[:space:]]*-)에서만 매칭 — 본문 내 "P1 이슈" 등 오탐 방지
    if echo "$CODEX_TEXT" | grep -iqE "DECISION:[[:space:]]*BLOCK|patch is incorrect|\"overall_correctness\"[[:space:]]*:[[:space:]]*\"(incorrect|fail)" \
      || echo "$CODEX_TEXT" | grep -qE "^[[:space:]]*-[[:space:]]*\[P[01]\]"; then
      CODEX_VERDICT="BLOCK"
      CODEX_LINE="🚫 BLOCK"
    else
      CODEX_VERDICT="PASS"
      CODEX_SUMMARY=$(echo "$CODEX_TEXT" | grep -v "^$" | tail -3 | head -1 | head -c 120 || echo "")
      CODEX_LINE="✅ PASS${CODEX_SUMMARY:+ — ${CODEX_SUMMARY}}"
    fi
  else
    # codex 실행 실패 → SKIP (CLI 미설치와 동일 처리, 일관성 유지)
    # 주: 배포 전 실제 gate는 npm run review:gate (create-pr.sh Step 3) 에서 수행됨
    CODEX_VERDICT="SKIP"
    CODEX_LINE="⏭️ SKIP (codex 실행 실패 — 인증/네트워크 확인 권장)"
  fi
else
  echo -e "${YELLOW}[review-summary] codex CLI 없음 — Codex gate 건너뜀${NC}"
fi

# ── 4. 코멘트 생성 ──────────────────────────────────────────────────────────
# 봇 리뷰 테이블: 환경변수로 주입 가능, 없으면 플레이스홀더
BOT_TABLE="${BOT_REVIEW_TABLE:-"| (봇) | (지적 내용) | [채택] / [기각] | (처리 내용) |"}"

COMMENT="$(cat <<EOF
## 리뷰 종합

### 봇 리뷰 채택/기각
| 봇 | 지적 | 판단 | 처리 |
|---|---|---|---|
${BOT_TABLE}

### 최종 검토

> **🤖 code-reviewer (Claude Opus)**
> ${OPUS_LINE}

> **🔍 Codex Gate**
> ${CODEX_LINE}

---
🤖 Generated by Claude Code [claude-sonnet-4-6]
EOF
)"

# ── 5. GitHub PR 코멘트 게시 ─────────────────────────────────────────────────
echo -e "${BLUE}[review-summary] PR #${PR_NUMBER}에 코멘트 게시 중...${NC}"
gh pr comment "$PR_NUMBER" --body "$COMMENT"

echo ""
echo -e "${GREEN}[review-summary] ✅ 완료 — PR #${PR_NUMBER}${NC}"
echo -e "${GREEN}[review-summary] Opus: ${OPUS_VERDICT} / Codex: ${CODEX_VERDICT}${NC}"

# 둘 다 PASS가 아니면 경고
if [ "$OPUS_VERDICT" != "PASS" ] || { [ "$CODEX_VERDICT" != "PASS" ] && [ "$CODEX_VERDICT" != "SKIP" ]; }; then
  echo -e "${RED}[review-summary] ⚠️  BLOCK 있음 — 수정 후 재실행, 머지 금지${NC}"
  exit 1
fi
