#!/usr/bin/env bash
# review-summary.sh — 리뷰 종합 코멘트 자동 생성 & GitHub PR에 게시
#
# 사용법: npm run review:summary
#   1. 현재 브랜치의 PR 번호 자동 감지
#   2. code-reviewer (Opus) 재실행 → 결과 추출
#   3. Codex gate 재실행 → 결과 추출
#   4. 리뷰 종합 코멘트 생성 → gh pr comment 게시
#
# 봇 리뷰(Gemini/Copilot/CodeRabbit) 채택/기각 내용은 스크립트 실행 전
# BOT_REVIEW_TABLE 환경변수로 전달하거나, 생성된 코멘트에 직접 편집 가능.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

BRANCH=$(git rev-parse --abbrev-ref HEAD)
SAFE_BRANCH="${BRANCH//\//-}"
REVIEW_FILE=".tmp/code-review-${SAFE_BRANCH}.md"

echo -e "${BLUE}[review-summary] 브랜치: ${BRANCH}${NC}"

# ── 1. PR 번호 감지 ──────────────────────────────────────────────────────────
PR_NUMBER=$(gh pr view "$BRANCH" --json number --jq '.number' 2>/dev/null || echo "")
if [ -z "$PR_NUMBER" ]; then
  echo -e "${RED}[review-summary] 현재 브랜치에 열린 PR 없음. PR 생성 후 실행하세요.${NC}"
  exit 1
fi
echo -e "${GREEN}[review-summary] PR #${PR_NUMBER} 감지${NC}"

# ── 2. code-reviewer (Opus) 재실행 ───────────────────────────────────────────
echo -e "${BLUE}[review-summary] code-reviewer (Opus) 실행 중...${NC}"
# 구 artifact 삭제 — 이전 실행 결과(다른 커밋)가 남아 있을 경우 스테일 PASS/BLOCK 방지
rm -f "$REVIEW_FILE"
bash scripts/run-code-reviewer.sh || true  # BLOCK 시에도 artifact는 저장됨 — 스크립트 중단 방지

if [ ! -f "$REVIEW_FILE" ]; then
  echo -e "${RED}[review-summary] 리뷰 artifact 없음: ${REVIEW_FILE}${NC}"
  exit 1
fi

# verdict 추출: tail -1 로 최종 판정 기준 (파일에 BLOCK 후 PASS 순서 보장 안 됨)
# grep 매칭 성공 시 cut도 exit 0 → || echo "UNKNOWN" 미도달 → 빈값 체크 필요
_opus_verdict_raw=$(grep -oE "VERDICT: (PASS|BLOCK)" "$REVIEW_FILE" | tail -1 || true)
OPUS_VERDICT=$(echo "$_opus_verdict_raw" | cut -d' ' -f2)
[ -z "$OPUS_VERDICT" ] && OPUS_VERDICT="UNKNOWN"
# 주요 소견: PASS 시 성공 메시지, BLOCK 시 첫 번째 CRITICAL/HIGH 지적사항
if [ "$OPUS_VERDICT" = "PASS" ]; then
  OPUS_SUMMARY=$(grep -m1 "VERDICT: PASS\|지적사항 없음\|이상 없음" "$REVIEW_FILE" \
    | sed 's/\*\*//g' | head -c 100 || echo "")
  OPUS_LINE="✅ PASS${OPUS_SUMMARY:+ — ${OPUS_SUMMARY}}"
else
  OPUS_SUMMARY=$(grep -m1 "\[CRITICAL\]\|\[HIGH\]" "$REVIEW_FILE" \
    | sed 's/\*\*//g' | head -c 120 || echo "세부 내용은 artifact 참조")
  OPUS_LINE="🚫 BLOCK — ${OPUS_SUMMARY:-재수정 필요}"
fi

# ── 3. Gemini gate 재실행 ────────────────────────────────────────────────────
GEMINI_VERDICT="SKIP"
GEMINI_LINE="⏭️ SKIP (gemini CLI 미설치)"

if command -v gemini &>/dev/null; then
  echo -e "${BLUE}[review-summary] Gemini gate 실행 중...${NC}"
  set +e
  GEMINI_TEXT=$(bash scripts/gemini-review-gate.sh warn origin/main 2>&1)
  GEMINI_EXIT=$?
  set -e
  echo "$GEMINI_TEXT"
  if [ "$GEMINI_EXIT" -eq 0 ]; then
    GEMINI_VERDICT="PASS"
    GEMINI_SUMMARY=$(echo "$GEMINI_TEXT" | grep -v "^\[gemini-gate\]" | grep -v "^$" | tail -2 | head -1 | head -c 120 || echo "")
    GEMINI_LINE="✅ PASS${GEMINI_SUMMARY:+ — ${GEMINI_SUMMARY}}"
  else
    GEMINI_VERDICT="BLOCK"
    GEMINI_BLOCK_DETAIL=$(echo "$GEMINI_TEXT" | grep -iE 'P0|P1|BLOCK|critical|bug' | head -3 | sed 's/^/  /' || echo "")
    GEMINI_LINE="🚫 BLOCK${GEMINI_BLOCK_DETAIL:+
${GEMINI_BLOCK_DETAIL}}"
  fi
else
  echo -e "${YELLOW}[review-summary] gemini CLI 없음 — Gemini gate 건너뜀${NC}"
fi

# ── 4. 코멘트 생성 ──────────────────────────────────────────────────────────
# 봇 리뷰 테이블: 환경변수로 주입 가능, 없으면 플레이스홀더
BOT_TABLE="${BOT_REVIEW_TABLE:-"| (봇) | (지적 내용) | [채택] / [기각] | (처리 내용) |"}"

COMMENT="$(cat <<EOF
## 리뷰 종합

### 봇 리뷰 채택/기각
| 봇 | 지적 | 판단 | 처리 |
|---|---|---|---|
${BOT_TABLE}

### 최종 검토

> **🤖 code-reviewer (Claude Opus)**
> ${OPUS_LINE}

> **✨ Gemini gate (gemini-3.1-pro-preview)**
> ${GEMINI_LINE}

---
🤖 Generated by Claude Code [claude-sonnet-4-6]
EOF
)"

# ── 5. GitHub PR 코멘트 게시 ─────────────────────────────────────────────────
echo -e "${BLUE}[review-summary] PR #${PR_NUMBER}에 코멘트 게시 중...${NC}"
gh pr comment "$PR_NUMBER" --body "$COMMENT"

echo ""
echo -e "${GREEN}[review-summary] ✅ 완료 — PR #${PR_NUMBER}${NC}"
echo -e "${GREEN}[review-summary] Opus: ${OPUS_VERDICT} / Gemini: ${GEMINI_VERDICT}${NC}"

if [ "$OPUS_VERDICT" != "PASS" ]; then
  echo -e "${RED}[review-summary] ⚠️  BLOCK — 수정 후 재실행, 머지 금지${NC}"
  exit 1
fi

if [ "$GEMINI_VERDICT" = "BLOCK" ]; then
  echo -e "${YELLOW}[review-summary] ⚠️  Opus PASS + Gemini BLOCK — Gemini 지적 검토 권장 (Opus 우선 신뢰)${NC}"
fi
